graða	ADJ;ACC;FEM;SG 
graðar	ADJ;FEM;PL
graðar	ADJ;ACC;MASC;PL
graðir	ADJ;NOM;MASC;PL
graðar	ADJ;GEN;FEM;SG
graðan	ADJ;ACC;MASC;SG
grað	ADJ;NEUT;PL
graður	ADJ;NOM;MASC;SG
graða	ADJ;GEN;MASC;PL
gratt	ADJ;NOM/ACC;NEUT;SG
graðum	ADJ;DAT;NEUT;SG
grað	ADJ;NOM;FEM;SG
graðs	ADJ;GEN;MASC;SG
graðari	ADJ;DAT;FEM;SG
graðum	ADJ;DAT;MASC;PL
graðum	ADJ;DAT;MASC;SG
graðs	ADJ;GEN;NEUT;SG

greivanna	N;DEF;GEN;PL
greivan	N;DEF;ACC;SG
greivunum	N;DEF;DAT;PL
greivar	N;INDF;ACC;PL
greiva	N;INDF;DAT;SG
greiva	N;INDF;ACC;SG
greivans	N;DEF;GEN;SG
greivi	N;INDF;NOM;SG
greivar	N;INDF;NOM;PL
greivum	N;INDF;DAT;PL
greivin	N;DEF;NOM;SG
greiva	N;INDF;GEN;SG
greivanum	N;DEF;DAT;SG
greivarnar	N;DEF;ACC;PL
greivarnir	N;DEF;NOM;PL
greiva	N;INDF;GEN;PL

greið	V;IMP;2;SG
greiddu	V;IND;PST;3
greiðir	V;IND;PRS;3;SG
greiði	V;IND;PRS;1;SG
greiðir	V;IND;PRS;2;SG
greiddi	V;IND;PST;3;SG
greiðandi	V.PTCP.PRS
greiða	V;NFIN
greiðið	V;IMP;2;PL
greiða	V;IND;PRS;3
greiddi	V;IND;PST;1;SG
greitt	V.CVB
greiddur	V.PTCP.PST
greiddi	V;IND;PST;2;SG
